name: untitled
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  splash_screen_view: ^3.0.0
  accordion: ^2.1.2
  url_launcher: ^6.0.18
  simple_speed_dial: ^0.1.3
  share: ^2.0.4
  in_app_review: ^2.0.4
  google_mobile_ads: ^1.0.1
  fluttertoast: ^8.0.8
  wiredash: ^0.7.0+1
  cool_alert: ^1.1.0

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter



  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
  #   - images/a_dot_ham.jpeg



  # example:
  fonts:
    - family: Dongle-Regular
      fonts:
        - asset: images/fonts/Dongle-Regular.ttf
        - asset: images/fonts/Rancho-Regular.ttf
          style: italic
    - family: Rancho-Regular
      fonts:
        - asset: images/fonts/Rancho-Regular.ttf
    - family: Satisfy-Regular
      fonts:
        - asset: images/fonts/Satisfy-Regular.ttf


